apiVersion: v1
kind: Service
metadata:
  name: {{ include "openmpi-cluster.fullname" . }}
  labels:
    {{- include "openmpi-cluster.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 8080
      protocol: TCP
      name: web
    - port: 22
      protocol: TCP
      name: ssh
  selector:
    {{- include "openmpi-cluster.selectorLabels" . | nindent 4 }}
