apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "openmpi-cluster.fullname" . }}
  labels:
    {{- include "openmpi-cluster.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "openmpi-cluster.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openmpi-cluster.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openmpi-cluster.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: openmpi
          securityContext:
            {{- if not .Values.sharedVolume.enabled }}
            privileged: true
            {{- with .Values.securityContext }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- else }}
            {{- toYaml .Values.securityContext | nindent 12 }}
            {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.settings.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.settings.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
            - name: ssh
              containerPort: 22
              protocol: TCP
          env:
            - name: CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: openmpi
                  resource: limits.cpu
                  divisor: "0"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NUM
              value: {{ .Values.replicaCount }}
            - name: NFS_MODE
              value: {{ if not .Values.sharedVolume.enabled }}ON{{ else }}OFF{{ end }}
            - name: TASK_MULTIPLIER
              value: {{ .Values.settings.taskMultiplier }}
            - name: SERVICE_NAME
              value: {{ include "openmpi-cluster.fullname" . }}
          volumeMounts:
          - name: shared-storage
            mountPath: /cloud
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: {{ include "openmpi-cluster.fullname" . }}
