{{- $NFS_MODE := "OFF" -}}
{{- if not .Values.sharedVolume.enabled }}
  {{- $NFS_MODE := "ON" }}
{{- end}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "openmpi-cluster.fullname" . }}
  labels:
    {{- include "openmpi-cluster.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "openmpi-cluster.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openmpi-cluster.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openmpi-cluster.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-etc-hosts
          image: busybox:1.28
          command:
            - sh
            - -c
            - |
              cp /etc/hosts /hosts/hosts
              for i in $(seq 0 $((NODE_NUM - 1)))
              do
                if [ $NODE_NUM -eq 1 ]
                then
                  host=$NODE_NAME
                  fhost=$NODE_NAME
                else
                  host="${NODE_NAME%-*}-${i}"
                  fhost="${NODE_NAME%-*}-${i}.${SERVICE_NAME}"
                  fhost=${host%.}
                fi
                
                host_ip=`ping  -c1 ${fhost} | head -n 1 | awk '{print $3}' | tr -d '():'`
                
                echo "${host_ip} ${host}" >> /hosts/hosts
              done
          env:
            - name: CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: openmpi
                  resource: limits.cpu
                  divisor: "0"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NUM
              value: {{ .Values.replicaCount | quote }}
          volumeMounts:
            - name: etc-hosts-volume
              mountPath: /hosts
      containers:
        - name: openmpi
          securityContext:
            {{- if not .Values.sharedVolume.enabled }}
            privileged: true
            {{- with .Values.securityContext }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- else }}
            {{- toYaml .Values.securityContext | nindent 12 }}
            {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.settings.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.settings.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
            - name: ssh
              containerPort: 22
              protocol: TCP
          env:
            - name: CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: openmpi
                  resource: limits.cpu
                  divisor: "0"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NUM
              value: {{ .Values.replicaCount | quote }}
            - name: NFS_MODE
              value: {{ $NFS_MODE | quote }}
            - name: TASK_MULTIPLIER
              value: {{ .Values.settings.taskMultiplier | quote }}
            - name: SERVICE_NAME
              value: {{ include "openmpi-cluster.fullname" . }}
          volumeMounts:
          - name: etc-hosts-volume
            mountPath: /etc/hosts
            subPath: hosts
          {{- if .Values.sharedVolume.enabled }}
          - name: shared-storage
            mountPath: /cloud
          {{- end }}
          {{- if .Values.sharedMemory.enabled }}
          - name: dshm
            mountPath: /dev/shm
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                {{- include "openmpi-cluster.selectorLabels" . | nindent 16 }}
            topologyKey: "kubernetes.io/hostname"
        {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: etc-hosts-volume
        emptyDir: {}
      {{- if .Values.sharedVolume.enabled }}
      - name: shared-storage
        persistentVolumeClaim:
          claimName: {{ include "openmpi-cluster.fullname" . }}
      {{- end }}
      {{- if .Values.sharedMemory.enabled }}
      - name: dshm
      {{- end }}
        {{- if eq .Values.sharedMemory.storageClass "none" }}
        emptyDir:
          medium: "Memory"
          sizeLimit: {{ .Values.sharedMemory.size }}
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ include "openmpi-cluster.fullname" . }}-dshm
        {{- end }}
